#!/bin/bash


DIR=$(dirname $0)

config=`$DIR/printlayout.sh`
file="$DIR/$config.sh"

if [[ -f $file ]]; then
    $file
else 
    echo "no setup for screen $file found.  Use Arandr to make one";
fi

sh $DIR/background.sh
